#############################################################################
# Makefile for building: tengu
# Generated by qmake (3.0) (Qt 5.3.2)
# Project:  tengu.pro
# Template: subdirs
# Command: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -o Makefile tengu.pro
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
SUBTARGETS    =  \
		sub-tengu \
		sub-simulators


sub-tengu-qmake_all:  FORCE
	@test -d tengu/ || mkdir -p tengu/
	cd tengu/ && $(QMAKE) /root/work/tenguai/tengu/tengu.pro -o Makefile
	cd tengu/ && $(MAKE) -f Makefile qmake_all
sub-tengu: FORCE
	@test -d tengu/ || mkdir -p tengu/
	cd tengu/ && ( test -e Makefile || $(QMAKE) /root/work/tenguai/tengu/tengu.pro -o Makefile ) && $(MAKE) -f Makefile
sub-tengu-make_first-ordered: FORCE
	@test -d tengu/ || mkdir -p tengu/
	cd tengu/ && ( test -e Makefile || $(QMAKE) /root/work/tenguai/tengu/tengu.pro -o Makefile ) && $(MAKE) -f Makefile 
sub-tengu-make_first: FORCE
	@test -d tengu/ || mkdir -p tengu/
	cd tengu/ && ( test -e Makefile || $(QMAKE) /root/work/tenguai/tengu/tengu.pro -o Makefile ) && $(MAKE) -f Makefile 
sub-tengu-all-ordered: FORCE
	@test -d tengu/ || mkdir -p tengu/
	cd tengu/ && ( test -e Makefile || $(QMAKE) /root/work/tenguai/tengu/tengu.pro -o Makefile ) && $(MAKE) -f Makefile all
sub-tengu-all: FORCE
	@test -d tengu/ || mkdir -p tengu/
	cd tengu/ && ( test -e Makefile || $(QMAKE) /root/work/tenguai/tengu/tengu.pro -o Makefile ) && $(MAKE) -f Makefile all
sub-tengu-clean-ordered: FORCE
	@test -d tengu/ || mkdir -p tengu/
	cd tengu/ && ( test -e Makefile || $(QMAKE) /root/work/tenguai/tengu/tengu.pro -o Makefile ) && $(MAKE) -f Makefile clean
sub-tengu-clean: FORCE
	@test -d tengu/ || mkdir -p tengu/
	cd tengu/ && ( test -e Makefile || $(QMAKE) /root/work/tenguai/tengu/tengu.pro -o Makefile ) && $(MAKE) -f Makefile clean
sub-tengu-distclean-ordered: FORCE
	@test -d tengu/ || mkdir -p tengu/
	cd tengu/ && ( test -e Makefile || $(QMAKE) /root/work/tenguai/tengu/tengu.pro -o Makefile ) && $(MAKE) -f Makefile distclean
sub-tengu-distclean: FORCE
	@test -d tengu/ || mkdir -p tengu/
	cd tengu/ && ( test -e Makefile || $(QMAKE) /root/work/tenguai/tengu/tengu.pro -o Makefile ) && $(MAKE) -f Makefile distclean
sub-tengu-install_subtargets-ordered: FORCE
	@test -d tengu/ || mkdir -p tengu/
	cd tengu/ && ( test -e Makefile || $(QMAKE) /root/work/tenguai/tengu/tengu.pro -o Makefile ) && $(MAKE) -f Makefile install
sub-tengu-install_subtargets: FORCE
	@test -d tengu/ || mkdir -p tengu/
	cd tengu/ && ( test -e Makefile || $(QMAKE) /root/work/tenguai/tengu/tengu.pro -o Makefile ) && $(MAKE) -f Makefile install
sub-tengu-uninstall_subtargets-ordered: FORCE
	@test -d tengu/ || mkdir -p tengu/
	cd tengu/ && ( test -e Makefile || $(QMAKE) /root/work/tenguai/tengu/tengu.pro -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-tengu-uninstall_subtargets: FORCE
	@test -d tengu/ || mkdir -p tengu/
	cd tengu/ && ( test -e Makefile || $(QMAKE) /root/work/tenguai/tengu/tengu.pro -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-simulators-qmake_all: sub-tengu-qmake_all FORCE
	@test -d simulators/ || mkdir -p simulators/
	cd simulators/ && $(QMAKE) /root/work/tenguai/simulators/simulators.pro -o Makefile
	cd simulators/ && $(MAKE) -f Makefile qmake_all
sub-simulators: sub-tengu FORCE
	@test -d simulators/ || mkdir -p simulators/
	cd simulators/ && ( test -e Makefile || $(QMAKE) /root/work/tenguai/simulators/simulators.pro -o Makefile ) && $(MAKE) -f Makefile
sub-simulators-make_first-ordered: sub-tengu-make_first-ordered  FORCE
	@test -d simulators/ || mkdir -p simulators/
	cd simulators/ && ( test -e Makefile || $(QMAKE) /root/work/tenguai/simulators/simulators.pro -o Makefile ) && $(MAKE) -f Makefile 
sub-simulators-make_first: sub-tengu-make_first FORCE
	@test -d simulators/ || mkdir -p simulators/
	cd simulators/ && ( test -e Makefile || $(QMAKE) /root/work/tenguai/simulators/simulators.pro -o Makefile ) && $(MAKE) -f Makefile 
sub-simulators-all-ordered: sub-tengu-all-ordered  FORCE
	@test -d simulators/ || mkdir -p simulators/
	cd simulators/ && ( test -e Makefile || $(QMAKE) /root/work/tenguai/simulators/simulators.pro -o Makefile ) && $(MAKE) -f Makefile all
sub-simulators-all: sub-tengu-all FORCE
	@test -d simulators/ || mkdir -p simulators/
	cd simulators/ && ( test -e Makefile || $(QMAKE) /root/work/tenguai/simulators/simulators.pro -o Makefile ) && $(MAKE) -f Makefile all
sub-simulators-clean-ordered: sub-tengu-clean-ordered  FORCE
	@test -d simulators/ || mkdir -p simulators/
	cd simulators/ && ( test -e Makefile || $(QMAKE) /root/work/tenguai/simulators/simulators.pro -o Makefile ) && $(MAKE) -f Makefile clean
sub-simulators-clean: sub-tengu-clean FORCE
	@test -d simulators/ || mkdir -p simulators/
	cd simulators/ && ( test -e Makefile || $(QMAKE) /root/work/tenguai/simulators/simulators.pro -o Makefile ) && $(MAKE) -f Makefile clean
sub-simulators-distclean-ordered: sub-tengu-distclean-ordered  FORCE
	@test -d simulators/ || mkdir -p simulators/
	cd simulators/ && ( test -e Makefile || $(QMAKE) /root/work/tenguai/simulators/simulators.pro -o Makefile ) && $(MAKE) -f Makefile distclean
sub-simulators-distclean: sub-tengu-distclean FORCE
	@test -d simulators/ || mkdir -p simulators/
	cd simulators/ && ( test -e Makefile || $(QMAKE) /root/work/tenguai/simulators/simulators.pro -o Makefile ) && $(MAKE) -f Makefile distclean
sub-simulators-install_subtargets-ordered: sub-tengu-install_subtargets-ordered  FORCE
	@test -d simulators/ || mkdir -p simulators/
	cd simulators/ && ( test -e Makefile || $(QMAKE) /root/work/tenguai/simulators/simulators.pro -o Makefile ) && $(MAKE) -f Makefile install
sub-simulators-install_subtargets: sub-tengu-install_subtargets FORCE
	@test -d simulators/ || mkdir -p simulators/
	cd simulators/ && ( test -e Makefile || $(QMAKE) /root/work/tenguai/simulators/simulators.pro -o Makefile ) && $(MAKE) -f Makefile install
sub-simulators-uninstall_subtargets-ordered: sub-tengu-uninstall_subtargets-ordered  FORCE
	@test -d simulators/ || mkdir -p simulators/
	cd simulators/ && ( test -e Makefile || $(QMAKE) /root/work/tenguai/simulators/simulators.pro -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-simulators-uninstall_subtargets: sub-tengu-uninstall_subtargets FORCE
	@test -d simulators/ || mkdir -p simulators/
	cd simulators/ && ( test -e Makefile || $(QMAKE) /root/work/tenguai/simulators/simulators.pro -o Makefile ) && $(MAKE) -f Makefile uninstall

Makefile: tengu.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_declarative.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_declarative_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		tengu.pro
	$(QMAKE) -o Makefile tengu.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_clucene_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_declarative.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_declarative_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioning.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_x11extras.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
tengu.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile tengu.pro

qmake_all: sub-tengu-qmake_all sub-simulators-qmake_all FORCE

make_first: sub-tengu-make_first-ordered sub-simulators-make_first-ordered FORCE
all: sub-tengu-all-ordered sub-simulators-all-ordered FORCE
clean: sub-tengu-clean-ordered sub-simulators-clean-ordered FORCE
distclean: sub-tengu-distclean-ordered sub-simulators-distclean-ordered FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-tengu-install_subtargets-ordered sub-simulators-install_subtargets-ordered FORCE
uninstall_subtargets: sub-tengu-uninstall_subtargets-ordered sub-simulators-uninstall_subtargets-ordered FORCE

sub-tengu-check_ordered:
	@test -d tengu/ || mkdir -p tengu/
	cd tengu/ && ( test -e Makefile || $(QMAKE) /root/work/tenguai/tengu/tengu.pro -o Makefile ) && $(MAKE) -f Makefile check
sub-simulators-check_ordered: sub-tengu-check_ordered 
	@test -d simulators/ || mkdir -p simulators/
	cd simulators/ && ( test -e Makefile || $(QMAKE) /root/work/tenguai/simulators/simulators.pro -o Makefile ) && $(MAKE) -f Makefile check
check: sub-tengu-check_ordered sub-simulators-check_ordered
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

